// Seam 1 纯函数:会话标题的噪声剥离。
// **形态取自真实采样,不是照 spec 清单想象**(2026-08-02,297 个真实 Claude 会话):
// Warmup 188、[cron:…] 92、caveat 13、slash 命令 2;调研期清单里的
// 「Conversation info」在采样里未出现,故不为它写规则。
import { describe, it, expect } from 'vitest'
import { realUserText, titleFrom } from './session-title'

describe('realUserText(单条消息 → 真实提问 | null)', () => {
  it('普通提问原样返回,并归一空白', () => {
    expect(realUserText('  帮我修一个   布局 bug\n\n谢谢  ')).toBe('帮我修一个 布局 bug 谢谢')
  })

  it('空白与空串视为噪声', () => {
    expect(realUserText('')).toBeNull()
    expect(realUserText('   \n\t ')).toBeNull()
  })

  // 真实占比最高的一种:整条消息就是这一个词(采样 188/297)
  it('Warmup:整条丢弃', () => {
    expect(realUserText('Warmup')).toBeNull()
    expect(realUserText('  Warmup \n')).toBeNull()
  })

  it('Warmup 只在整条完全相等时才算噪声——真提问里出现该词不受影响', () => {
    expect(realUserText('Warmup 这个词是哪来的?')).toBe('Warmup 这个词是哪来的?')
  })

  // 真实形态:[cron:<uuid> <名字>] 后面跟的是**真正的指令**,不能连着一起丢
  it('cron 标记:只剥方括号,保留后面的指令', () => {
    expect(
      realUserText('[cron:95a214a4-0021-44ea-a831-f5c851b11d77 hackernews-daily-top5] 用 Hacker News 官方 API 获取今日最热门的 5 个话题')
    ).toBe('用 Hacker News 官方 API 获取今日最热门的 5 个话题')
  })

  it('cron 标记后面没内容 → 整条丢弃', () => {
    expect(realUserText('[cron:abc def]')).toBeNull()
  })

  it('caveat 块整条丢弃', () => {
    expect(
      realUserText('<local-command-caveat>Caveat: The messages below were generated by the user while running local commands.</local-command-caveat>')
    ).toBeNull()
  })

  // 第二层噪声:剥掉 caveat / 命令调用之后才浮出来的(实测 7/144)
  it('local-command 输出整条丢弃(与 caveat 同族)', () => {
    expect(realUserText('<local-command-stdout>Set model to Fable 5</local-command-stdout>')).toBeNull()
  })

  it('真提问里带图片标记不算噪声——只见过一例,不为它写剥离规则', () => {
    expect(realUserText('[Image #1] 这个图中日期显示稀疏')).toBe('[Image #1] 这个图中日期显示稀疏')
  })

  it('skill 正文注入整条丢弃', () => {
    expect(realUserText('Base directory for this skill: /Users/x/.claude/skills/tdd # TDD 红先于绿')).toBeNull()
  })

  // 真实形态:真正的用户输入在 command-args 里
  it('slash 命令:取 command-args 的内容', () => {
    expect(
      realUserText(
        '<command-message>superpowers:brainstorming</command-message> <command-name>/superpowers:brainstorming</command-name> <command-args>我想开发一个自学用的 app</command-args>'
      )
    ).toBe('我想开发一个自学用的 app')
  })

  it('slash 命令 args 为空(如 /clear)→ 整条丢弃', () => {
    expect(
      realUserText('<command-name>/clear</command-name> <command-message>clear</command-message> <command-args></command-args>')
    ).toBeNull()
  })

  it('有 command-name 但完全没有 args 标签 → 整条丢弃(是命令调用不是提问)', () => {
    expect(realUserText('<command-name>/compact</command-name>')).toBeNull()
  })
})

describe('titleFrom(消息序列 → 标题)', () => {
  // 真实形态:caveat 之后跟 /clear,真正的提问在第三条——必须逐条向后找
  it('噪声不止一条时继续向后找', () => {
    expect(
      titleFrom([
        '<local-command-caveat>Caveat: …</local-command-caveat>',
        '<command-name>/clear</command-name> <command-message>clear</command-message> <command-args></command-args>',
        '继续会话查看功能:读 spec',
        '再来一句'
      ])
    ).toBe('继续会话查看功能:读 spec')
  })

  it('全是噪声 → null(调用方据此判定不入列)', () => {
    expect(titleFrom(['Warmup'])).toBeNull()
    expect(titleFrom([])).toBeNull()
    expect(titleFrom(['Warmup', '<local-command-caveat>x</local-command-caveat>'])).toBeNull()
  })

  it('超长标题截断并加省略号', () => {
    const t = titleFrom(['长'.repeat(200)])
    expect(t).not.toBeNull()
    expect([...(t as string)].length).toBeLessThanOrEqual(61)
    expect(t?.endsWith('…')).toBe(true)
  })

  it('不足上限的标题不加省略号', () => {
    expect(titleFrom(['短问题'])).toBe('短问题')
  })
})
