// A seam 1 pure function: stripping noise out of session titles.
// **The shapes come from real sampling, not from imagining the spec's list** (2026-08-02, 297 real Claude
// sessions):
// Warmup 188, [cron:…] 92, caveat 13, slash commands 2. The "Conversation info" on the research-phase list
// did not appear in the sample, so no rule is written for it.
import { describe, it, expect } from 'vitest'
import { clipTitle, realUserText } from './session-title'

describe('realUserText (one message → the real question, or null)', () => {
  it('an ordinary question is returned as is, with whitespace normalised', () => {
    expect(realUserText('  帮我修一个   布局 bug\n\n谢谢  ')).toBe('帮我修一个 布局 bug 谢谢')
  })

  it('whitespace and the empty string count as noise', () => {
    expect(realUserText('')).toBeNull()
    expect(realUserText('   \n\t ')).toBeNull()
  })

  // The most common shape by far: the whole message is that one word (188/297 in the sample)
  it('Warmup: the whole message is discarded', () => {
    expect(realUserText('Warmup')).toBeNull()
    expect(realUserText('  Warmup \n')).toBeNull()
  })

  it('Warmup counts as noise only on exact equality — a real question containing the word is unaffected', () => {
    expect(realUserText('Warmup 这个词是哪来的?')).toBe('Warmup 这个词是哪来的?')
  })

  // The real shape: what follows [cron:<uuid> <name>] is **the actual instruction** and must not be
  // discarded with it
  it('the cron marker: only the bracket is stripped, keeping the instruction after it', () => {
    expect(
      realUserText('[cron:95a214a4-0021-44ea-a831-f5c851b11d77 hackernews-daily-top5] 用 Hacker News 官方 API 获取今日最热门的 5 个话题')
    ).toBe('用 Hacker News 官方 API 获取今日最热门的 5 个话题')
  })

  it('nothing after the cron marker → the whole message is discarded', () => {
    expect(realUserText('[cron:abc def]')).toBeNull()
  })

  it('a caveat block is discarded whole', () => {
    expect(
      realUserText('<local-command-caveat>Caveat: The messages below were generated by the user while running local commands.</local-command-caveat>')
    ).toBeNull()
  })

  // The second layer of noise, surfacing only after caveat and command invocations are stripped
  // (measured 7/144)
  it('local-command output is discarded whole (the same family as caveat)', () => {
    expect(realUserText('<local-command-stdout>Set model to Fable 5</local-command-stdout>')).toBeNull()
  })

  it('an image marker inside a real question is not noise — seen once, and no stripping rule is written for it', () => {
    expect(realUserText('[Image #1] 这个图中日期显示稀疏')).toBe('[Image #1] 这个图中日期显示稀疏')
  })

  it('an injected skill body is discarded whole', () => {
    expect(realUserText('Base directory for this skill: /Users/x/.claude/skills/tdd # TDD 红先于绿')).toBeNull()
  })

  // The real shape: the user's actual input is inside command-args
  it('a slash command: take the contents of command-args', () => {
    expect(
      realUserText(
        '<command-message>superpowers:brainstorming</command-message> <command-name>/superpowers:brainstorming</command-name> <command-args>我想开发一个自学用的 app</command-args>'
      )
    ).toBe('我想开发一个自学用的 app')
  })

  it('a slash command with empty args (such as /clear) → the whole message is discarded', () => {
    expect(
      realUserText('<command-name>/clear</command-name> <command-message>clear</command-message> <command-args></command-args>')
    ).toBeNull()
  })

  it('a command-name with no args tag at all → discarded whole (it is a command invocation, not a question)', () => {
    expect(realUserText('<command-name>/compact</command-name>')).toBeNull()
  })
})

describe('clipTitle (a noise-stripped question → a title)', () => {
  // The responsibility of "walking forward to find the first real question" moved to the indexer on
  // 2026-08-04 (ticket 03b),
  // covered in question-index.test.ts (noise is not a question / no real question anywhere → an empty
  // index).
  // What remains here is truncation, plus one regression guard: clipTitle **must not** strip again.
  it('an over-long title is truncated by code point with an ellipsis added', () => {
    const t = clipTitle('长'.repeat(200))
    expect([...t]).toHaveLength(61)
    expect(t.endsWith('…')).toBe(true)
  })

  it('a title under the cap is returned as is, with no ellipsis', () => {
    expect(clipTitle('短问题')).toBe('短问题')
  })

  it('no longer strips — stripping is not idempotent, and a second pass would discard the already-stripped content as noise', () => {
    // `[cron:x] Warmup` strips through realUserText to 'Warmup'; if clipTitle stripped again
    // it would become null and the session would vanish from the list.
    expect(realUserText('[cron:abc 定时] Warmup')).toBe('Warmup')
    expect(clipTitle('Warmup')).toBe('Warmup')
  })
})
